title = "Hugo Template"
googleAnalytics = ""
disableFastRender = true
languageCode = "sl-sl"
defaultContentLanguage = "sl"

[params]
description = "To je opis te spletne strani"
image = "/media/brand/og-image.jpg"

[params.breakpoints]
  xs = 576
  sm = 768
  md = 992
  lg = 1200
  xl = 1440

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true
