title = "Hugo Template"
googleAnalytics = ""
disableFastRender = true
languageCode = "sl-sl"
defaultContentLanguage = "sl"

[params]
description = "Boilerplate projekt za Jamtstack projekte, ki temeljijo na tehnologijah Hugo in Netlify CMS."
image = "/media/brand/og-image.jpg"

[params.breakpoints]
  xs = 576
  sm = 768
  md = 992
  lg = 1200
  xl = 1440
  xxl = 1680
  xxxl = 1920

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true
