languageCode = "sl-sl"
title = "Hugo Template"
# baseURL is set automatically in netlify.toml
googleAnalytics = ""
disableFastRender = true
# enableRobotsTXT = true

[params]
  description = ""

[markup.goldmark.renderer]
  unsafe= true
