[build]
  publish = "public"
  command = "npm run lint && chmod +x ./bin/build.sh && ./bin/build.sh"

[build.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  GIT_LFS_ENABLED = "true"
