name: Pull Request Audits
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Wait for Netlify Preview
        uses: kamranayub/wait-for-netlify-action@2.0.0
        id: netflify-preview
        with:
          site_name: "hugo-template"
          max_timeout: 60
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - name: Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.netflify-preview.outputs.url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
